name: Upload dictionaries

on:
  push:
    branches:
      - master

jobs:
  update-dictionaries:
    name: Run latotale.py & Commit Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend repository
        uses: actions/checkout@v3
        with:
          repository: digital-magic-club/vrtx-backend
          token: ${{ secrets.VRTX_CI_TOKEN }}
          ref: master
          path: backend

      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: master

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "$GITHUB_WORKSPACE/backend/functions/dictionaries/requirements.txt"

      - name: Run latotale.py on merged dictionaries
        run: |
          python "$GITHUB_WORKSPACE/backend/functions/dictionaries/latotale.py" "$GITHUB_WORKSPACE/master/dictionaries/Dictionaries.md"

      - name: Check for Changes
        run: |
          cd "$GITHUB_WORKSPACE/master"
          git status
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          cd "$GITHUB_WORKSPACE/master"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dictionaries/Dictionaries.md
          git commit -m "Upload dictionaries"
          git push origin master

      - name: No Changes to Commit
        if: env.CHANGES_DETECTED == 'false'
        run: echo "No updates were made to dictionaries."
